### ISSUE TITLE
[Request] Add me to co-maintainers of some packages

### ISSUE THREAD

**Issue by Kristinita** [adgellida/chocolateyautomaticpackages#22]
[**My profile in Chocolatey**](https://chocolatey.org/profiles/oderzhimyi_Sashei).

Since you no longer update packages, I want to be a maintainer of these packages, have no maintainers except you:

+ AceStream
+ SopCast
+ Wassapp

Thanks.

**Comment by adgellida** [comment]
Approvation sended.
