### ISSUE TITLE
Package handover for OneDrive?

### ISSUE THREAD

**Issue by mattheyan** [adgellida/chocolateyautomaticpackages#23]
Hi Antonio,

Since you are no longer maintaining Chocolatey packages, would you be willing to let me take over the `OneDrive` package? Due to the fact that my employer would be relying on the package to service our customers, I would have to have exclusive control of the package. If you're not interested then I'll just use a different name, but I thought it would be good for others to be able to use it as well.

Thanks,
Bryan

**Comment by adgellida** [comment]
Right now I'm only [winsys](https://chocolatey.org/packages/winsys) maintainer. Now you're [OneDrive](https://chocolatey.org/packages/onedrive) maintainer, do that you want. Good luck!

**Comment by mattheyan** [comment]
Thanks! Do you mind if I remove you per the note above about my employer's requirements?

**Comment by adgellida** [comment]
I don't care.
