### ISSUE TITLE
Add a maintainer for the tinytask package?

### ISSUE THREAD

**Issue by teknowledgist** [adgellida/chocolateyautomaticpackages#28]
Hi.  I would like to assist with maintaining the [tinytask Chocolatey package](https://community.chocolatey.org/packages/tinytask).  Are you willing to add me?  

I opened an issue here because your Chocolatey profile won't accept messages and the admins want me to attempt communication with you.

Thanks!

**Comment by abejaranoh** [comment]
@teknowledgist here is the contact: https://github.com/adgellida

**Comment by teknowledgist** [comment]
Sure, but is opening this issue not enough?  Do I need to reach out via direct email rather than through the systems related to this Chocolatey package?
